# fly.toml file generated for go-nns on 2023-03-15T23:53:20-07:00

app = "go-nns"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sea"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8080"

[processes]
  app = "go-nns -public-addr /dns/nns.contact -http-addr :8080"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "udp"
  internal_port = 9971

  [[services.ports]]
    port = 9971

[[services]]
  protocol = "tcp"
  internal_port = 9971

  [[services.ports]]
    port = 9971

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

